%% merge_SMAP_NNsm_ETC.m
% Merge SMAP and NNsm using ETC-derived random error variances.
%
% Fusion rules
% ------------
% 1. SMAP and NNsm both valid, ETC error variances valid:
%       inverse-error-variance weighted average
% 2. Only SMAP valid:
%       retain SMAP
% 3. Only NNsm valid:
%       retain NNsm
% 4. Both valid, ETC weights unavailable:
%       equal-weight average
% 5. Both missing:
%       retain NaN
%
% Input assumptions
% -----------------
% - SMAP and NNsm have been preprocessed to the same 36-km EASE-Grid 2.0.
% - Each yearly file has size [lon x lat x 366].
% - ETC error variances were generated by the corresponding ETC scripts.
%
% Expected files
% --------------
% ETC/
%   ETC_ASCAT_SMAP_GLDAS.mat      variable: ERRVAR_SMAP
%   ETC_ASCAT_NNsm_GLDAS.mat      variable: ERRVAR_NNsm
%
% SMAP/
%   sm_yea_DYYYY.mat              variable: sm_yea_D
%
% NNsm/
%   NNsm_yearYYYY.mat             variable: NNsm_year
%
% Output
% ------
% fusion/fusion_YYYY.mat
%   fusion_SM      merged daily soil moisture
%   fusion_flag    fusion-source flag
%
% fusion_flag:
%   0 = both missing
%   1 = ETC-weighted fusion
%   2 = SMAP only
%   3 = NNsm only
%   4 = equal-weight fallback
%
% MATLAB: R2024a or later

%% Configuration

years = 2015:2024;

% Edit this path before running.
project_root = 'PATH_TO_PROJECT_DATA';

etc_dir  = fullfile(project_root, 'ETC');
smap_dir = fullfile(project_root, 'SMAP');
nnsm_dir = fullfile(project_root, 'NNsm');

out_dir = fullfile(project_root, 'fusion');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

etc_smap_file = fullfile(etc_dir, 'ETC_ASCAT_SMAP_GLDAS.mat');
etc_nnsm_file = fullfile(etc_dir, 'ETC_ASCAT_NNsm_GLDAS.mat');

%% ETC-based fusion weights

S = load(etc_smap_file, 'ERRVAR_SMAP');
ERRVAR_SMAP = single(S.ERRVAR_SMAP);

S = load(etc_nnsm_file, 'ERRVAR_NNsm');
ERRVAR_NNsm = single(S.ERRVAR_NNsm);
clear S

valid_weight = ...
    isfinite(ERRVAR_SMAP) & isfinite(ERRVAR_NNsm) & ...
    ERRVAR_SMAP > 0 & ERRVAR_NNsm > 0;

W_SMAP = nan(size(ERRVAR_SMAP), 'single');
W_NNsm = nan(size(ERRVAR_NNsm), 'single');

den = ERRVAR_SMAP + ERRVAR_NNsm;

% Inverse-error-variance weighting:
% w_SMAP = (1/err_SMAP) / [(1/err_SMAP) + (1/err_NNsm)]
%        = err_NNsm / (err_SMAP + err_NNsm)
W_SMAP(valid_weight) = ...
    ERRVAR_NNsm(valid_weight) ./ den(valid_weight);

W_NNsm(valid_weight) = ...
    ERRVAR_SMAP(valid_weight) ./ den(valid_weight);

clear den ERRVAR_SMAP ERRVAR_NNsm

%% Yearly fusion

for yy = years

    fprintf('Merging SMAP and NNsm for %d...\n', yy);

    smap_file = fullfile(smap_dir, sprintf('sm_yea_D%d.mat', yy));
    nnsm_file = fullfile(nnsm_dir, sprintf('NNsm_year%d.mat', yy));

    S = load(smap_file, 'sm_yea_D');
    SMAP = single(S.sm_yea_D);

    S = load(nnsm_file, 'NNsm_year');
    NNsm = single(S.NNsm_year);
    clear S

    [nlon, nlat, nt] = size(SMAP);

    fusion_SM   = nan(nlon, nlat, nt, 'single');
    fusion_flag = zeros(nlon, nlat, nt, 'uint8');

    for t = 1:nt

        smap_t = SMAP(:, :, t);
        nnsm_t = NNsm(:, :, t);

        valid_smap = isfinite(smap_t);
        valid_nnsm = isfinite(nnsm_t);

        weighted = valid_smap & valid_nnsm & valid_weight;
        only_smap = valid_smap & ~valid_nnsm;
        only_nnsm = ~valid_smap & valid_nnsm;
        fallback  = valid_smap & valid_nnsm & ~valid_weight;

        fusion_t = nan(nlon, nlat, 'single');
        flag_t   = zeros(nlon, nlat, 'uint8');

        % ETC-weighted fusion
        fusion_t(weighted) = ...
            W_SMAP(weighted) .* smap_t(weighted) + ...
            W_NNsm(weighted) .* nnsm_t(weighted);
        flag_t(weighted) = 1;

        % Single-product availability
        fusion_t(only_smap) = smap_t(only_smap);
        flag_t(only_smap) = 2;

        fusion_t(only_nnsm) = nnsm_t(only_nnsm);
        flag_t(only_nnsm) = 3;

        % Equal-weight fallback when both products are valid but
        % ETC-based weights are unavailable
        fusion_t(fallback) = ...
            0.5 .* smap_t(fallback) + ...
            0.5 .* nnsm_t(fallback);
        flag_t(fallback) = 4;

        fusion_SM(:, :, t)   = fusion_t;
        fusion_flag(:, :, t) = flag_t;
    end

    out_file = fullfile(out_dir, sprintf('fusion_%d.mat', yy));

    save(out_file, ...
        'fusion_SM', 'fusion_flag', ...
        '-v7.3');

    clear SMAP NNsm fusion_SM fusion_flag

end

fprintf('SMAP-NNsm fusion completed.\n');
